Gymnasium/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('members/', include('members.urls')),
    path('notifications/', include('notifications.urls')),
    path('reports/', include('reports.urls')),
    path('', include('accounts.urls'))
]

# for handling profile photos
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

members/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('add/', login_required(views.add_member), name='add_member'),
    path('search/', login_required(views.search_member), name='search_member'),
    path('view/', login_required(views.view_member), name='view_member'),
    path('delete/<int:id>/', login_required(views.delete_member), name='delete_member'),
    path('update/<int:id>/', login_required(views.update_member), name='update_member'),
    path('', login_required(views.members), name='members'),
]

notifications/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required

urlpatterns = [
    path('delete/<int:id>/', login_required(views.notification_delete), name='notification_delete'),
    path('', login_required(views.notifications), name='notifications'),
]

members/models.py
from django.db import models
from django.forms import ModelForm
from django import forms
import datetime

SUBSCRIPTION_TYPE_CHOICES = (
    ('gym', 'Gym'),
    ('cross_fit', 'Cross Fit'),
    ('gym_and_cross_fit', 'Gym + Cross Fit'),
    ('pt', 'Personal Training')
)

SUBSCRIPTION_PERIOD_CHOICES = (
    ('1', '1 Month'),
    ('2', '2 Months'),
    ('3', '3 Months'),
    ('4', '4 Months'),
    ('5', '5 Months'),
    ('6', '6 Months'),
    ('7', '7 Months'),
    ('8', '8 Months'),
    ('9', '9 Months'),
    ('10', '10 Months'),
    ('11', '11 Months'),
    ('12', '12 Months'),
)

FEE_STATUS = (
    ('paid', 'Paid'),
    ('pending', 'Pending'),
)

STATUS = (
    (0, 'Start'),
    (1, 'Stop'),
)

BATCH = (
    ('morning', 'Morning'),
    ('evening', 'Evening'),
)

class Member(models.Model):
    member_id = models.AutoField(primary_key=True)
    first_name = models.CharField(('First Name'), max_length=50)
    last_name = models.CharField(('Last Name'), max_length=50)
    mobile_number = models.CharField(('Mobile Number'), max_length=10, unique=True)
    email = models.EmailField(null=True, blank=True)
    address = models.CharField(max_length=300, blank=True)
    medical_history = models.CharField(('Medical History'), max_length=300, blank=True, default='None')
    admitted_on = models.DateField(auto_now_add=True)
    registration_date = models.DateField(('Registration Date'), default='dd/mm/yyyy')
    registration_upto = models.DateField()
    dob = models.DateField(default='dd/mm/yyyy')
    subscription_type  = models.CharField(
                                ('Subscription Type'),
                                max_length=30,
                                choices=SUBSCRIPTION_TYPE_CHOICES,
                                default=SUBSCRIPTION_TYPE_CHOICES[0][0]
                            )
    subscription_period = models.CharField(
                                ('Subscription Period'),
                                max_length=30,
                                choices=SUBSCRIPTION_PERIOD_CHOICES,
                                default=SUBSCRIPTION_PERIOD_CHOICES[0][0]
                            )
    amount = models.CharField(max_length=30)
    fee_status = models.CharField(
                                ('Fee Status'),
                                max_length=30,
                                choices=FEE_STATUS,
                                default=FEE_STATUS[0][0]
                            )
    batch = models.CharField(
                                max_length=30,
                                choices=BATCH,
                                default=BATCH[0][0]
                            )
    photo = models.FileField(upload_to='photos/', blank=True)
    notification = models.IntegerField(default=2, blank=True)
    stop = models.IntegerField(('Status'), choices=STATUS, default=STATUS[0][0], blank=True)

    def __str__(self):
        return self.first_name + ' ' + self.last_name

class AddMemberForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(AddMemberForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].error_messages = {'required': 'Please enter first name'}
        self.fields['last_name'].error_messages = {'required': 'Please enter last name'}

    class Meta:
        model = Member
        # fields = ['first_name', 'last_name', 'mobile_number', 'email', 'address', 'subscription_type', 'subscription_period', 'amount']
        fields = '__all__'
        exclude = ['registration_upto']
        widgets = {
        'registration_date': forms.DateInput(attrs={'class': 'datepicker form-control', 'type': 'date'}),
        'address': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
        'medical_history': forms.Textarea(attrs={'cols': 80, 'rows': 3}),
        'dob': forms.DateInput(attrs={'class': 'datepicker form-control', 'type': 'date'}),
        'photo': forms.FileInput(attrs={'accept': 'image/*;capture=camera'})
        }

    def clean_mobile_number(self, *args, **kwargs):
        mobile_number = self.cleaned_data.get('mobile_number')
        if not mobile_number.isdigit():
            raise forms.ValidationError('Mobile number should be a number')
        if Member.objects.filter(mobile_number=mobile_number).exists():
            raise forms.ValidationError('This mobile number has already been registered.')
        else:
            if len(str(mobile_number)) == 10:
                return mobile_number
            else:
                raise forms.ValidationError('Mobile number should be 10 digits long.')
        return mobile_number

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if not amount.isdigit():
            raise forms.ValidationError('Amount should be a number')
        return amount

    def clean(self):
        cleaned_data = super().clean()
        dob = cleaned_data.get('dob')
        first_name = cleaned_data.get('first_name').capitalize()
        last_name = cleaned_data.get('last_name').capitalize()
        queryset = Member.objects.filter(
                        first_name=first_name,
                        last_name=last_name,
                        dob=dob
                    ).count()
        if queryset > 0:
            raise forms.ValidationError('This member already exists!')


class SearchForm(forms.Form):
    search = forms.CharField(label='Search Member', max_length=100, required=False)

    def clean_search(self, *args, **kwargs):
        search = self.cleaned_data.get('search')
        if search == '':
            raise forms.ValidationError('Please enter a name in search box')
        return search

class UpdateMemberGymForm(forms.Form):
    registration_date   = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker        form-control', 'type': 'date'}),)
    registration_upto = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker form-control', 'type': 'date'}),)
    subscription_type  = forms.ChoiceField(choices=SUBSCRIPTION_TYPE_CHOICES)
    subscription_period = forms.ChoiceField(choices=SUBSCRIPTION_PERIOD_CHOICES)
    fee_status = forms.ChoiceField(choices=FEE_STATUS)
    amount = forms.CharField()
    batch = forms.ChoiceField(choices=BATCH)
    stop = forms.ChoiceField(label='Status', choices=STATUS)

    def clean_amount(self):
        amount = self.cleaned_data.get('amount')
        if not amount.isdigit():
            raise forms.ValidationError('Amount should be a number')
        return amount

class UpdateMemberInfoForm(forms.Form):
    first_name     = forms.CharField(max_length=50)
    last_name      = forms.CharField(max_length=50)
    photo          = forms.FileField(label='Update Photo', required=False)
    dob            = forms.DateField(widget=forms.DateInput(attrs={'class': 'datepicker        form-control', 'type': 'date'}),)

notifications/models.py
from django.db import models

# Create your models here.

notifications/views.py
from django.shortcuts import render, redirect
from members.models import Member, FEE_STATUS
import datetime
from django.db.models import Q
from .config import get_notification_count, run_notifier
import dateutil.relativedelta as delta
import dateutil.parser as parser
import datetime
from django.db.models.signals import post_save, pre_save
from .config import my_handler

# Create your views here.
def notifications(request):
    # run_notifier()
    morning_members_before = Member.objects.filter(
                                        Q(registration_upto__lte=datetime.datetime.now(),
                                        notification=1, batch='morning') |
                                        Q(fee_status='pending', notification=1, batch='morning')
                                        ).exclude(stop=1).order_by('first_name')
    morning_members_today = Member.objects.filter(
                                        registration_upto__gte=datetime.datetime.now(),
                                        registration_upto__lte=datetime.date.today() + datetime.timedelta(days=2),
                                        notification=1, batch='morning').exclude(stop=1).order_by('first_name')

    evening_members_before = Member.objects.filter(
                                        Q(registration_upto__lte=datetime.datetime.now(),
                                        notification=1, batch='evening') |
                                        Q(fee_status='pending', notification=1, batch='evening')
                                        ).exclude(stop=1).order_by('first_name')
    evening_members_today = Member.objects.filter(
                                        registration_upto__gte=datetime.datetime.now(),
                                        registration_upto__lte=datetime.date.today() + datetime.timedelta(days=2),
                                        notification=1, batch='evening').exclude(stop=1).order_by('first_name')

    context = {
        'subs_end_today_count': get_notification_count(),
        'morning_members_today': morning_members_today,
        'morning_members_before': morning_members_before,
        'evening_members_today': evening_members_today,
        'evening_members_before': evening_members_before,
    }
    # Entry.objects.filter(pub_date__date__gt=datetime.date(2005, 1, 1))
    return render(request, 'notifications.html', context)

def notification_delete(request, id):
    member = Member.objects.get(pk=id)
    member.notification = 0
    member.stop = 1
    post_save.disconnect(my_handler, sender=Member)
    member.save()
    post_save.connect(my_handler, sender=Member)
    return redirect('/notifications/')

# post_save.connect(my_handler, sender=Member)
# pre_save.connect(run_notifier, sender=Member)

notifications/templates/notifications.html
{% extends 'base.html' %}
{% load index %}

{% block content %}
    <ul class="nav nav-tabs nav-justified" id="myTab" role="tablist" style="margin-top: 3%">
      <li class="nav-item">
        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#morning" role="tab" aria-controls="home" aria-selected="true">Morning</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#evening" role="tab" aria-controls="profile" aria-selected="false">Evening</a>
      </li>
    </ul>

    <div class="tab-content" id="myTabContent">
      <div class="tab-pane fade show active" id="morning" role="tabpanel" aria-labelledby="home-tab">
        <h3 style="margin-top: 3%; margin-bottom: 3%">Due Today</h3>
        {% if morning_members_today %}
            <table class="table table-bordered">
                <thead class="thead-dark text-center">
                    <tr>
				   <th>Profile Photo</th>
                        <th>Name</th>
                        <th>DOB</th>
                        <th>Registration Date</th>
                        <th>Registration End</th>
                        <th>Subscription Type</th>
                        <th>Edit</th>
                        <th>Delete Notification</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for member in morning_members_today %}
                        <tr>
					<td><img src="{% if member.photo %}{{ member.photo.url }}{% else %}/media/default.jpg{% endif %}" class="img-fluid" width="100" height="100"></td>
                            <td>{{ member.first_name }} {{ member.last_name }}</td>
                            <td>{{ member.dob }}</td>
                            <td>{{ member.registration_date }}</td>
                            <td>{{ member.registration_upto }}</td>
                            <td>{{ member.get_subscription_type_display }}</td>
                            <td>
                                <a href="/members/update/{{ member.member_id }}/"><button class="btn btn-success">Edit</button>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="/notifications/delete/{{ member.member_id }}/"><button class="btn btn-danger">Delete</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
        <div class="row text-center">
            <div class="alert alert-warning col"> <strong>No Notifications</strong> </div>
        </div>
        {% endif %}

        <hr>

        <h3>Past Dues</h3>
        {% if morning_members_before %}
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
                <tr>
			    <th>Profile Photo</th>
                    <th>Name</th>
                    <th>DOB</th>
                    <th>Registration Date</th>
                    <th>Registration End</th>
                    <th>Subscription Type</th>
                    <th>Pending Month</th>
                    <th>Edit</th>
                    <th>Delete Notification</th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for member in morning_members_before %}
                    <tr>
				  <td><img src="{% if member.photo %}{{ member.photo.url }}{% else %}/media/default.jpg{% endif %}" class="img-fluid" width="100" height="100"></td>

                        <td>{{ member.first_name }} {{ member.last_name }}</td>
                        <td>{{ member.dob }}</td>
                        <td>{{ member.registration_date }}</td>
                        <td>{{ member.registration_upto }}</td>
                        <td>{{ member.get_subscription_type_display }}</td>
                        <td>{{ member.registration_upto|get_remaining_months}}</td>
                        <td>
                            <a href="/members/update/{{ member.member_id }}/"><button class="btn btn-success">Edit</button>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="/notifications/delete/{{ member.member_id }}/"><button class="btn btn-danger">Delete</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <div class="row text-center">
            <div class="alert alert-warning col"> <strong>No Notifications</strong> </div>
        </div>
        {% endif %}
      </div>

      <div class="tab-pane fade show" id="evening" role="tabpanel" aria-labelledby="home-tab">
        <h3 style="margin-top: 3%; margin-bottom: 3%">Due Today</h3>
        {% if evening_members_today %}
            <table class="table table-bordered">
                <thead class="thead-dark text-center">
                    <tr>
				  <th>Profile Photo</th>
                        <th>Name</th>
                        <th>DOB</th>
                        <th>Registration Date</th>
                        <th>Registration End</th>
                        <th>Subscription Type</th>
                        <th>Edit</th>
                        <th>Delete Notification</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for member in evening_members_today %}
                        <tr>
					 <td><img src="{% if member.photo %}{{ member.photo.url }}{% else %}/media/default.jpg{% endif %}" class="img-fluid" width="100" height="100"></td>

                            <td>{{ member.first_name }} {{ member.last_name }}</td>
                            <td>{{ member.dob }}</td>
                            <td>{{ member.registration_date }}</td>
                            <td>{{ member.registration_upto }}</td>
                            <td>{{ member.get_subscription_type_display }}</td>
                            <td>
                                <a href="/members/update/{{ member.member_id }}/"><button class="btn btn-success">Edit</button>
                                </a>
                            </td>
                            <td class="text-center">
                                <a href="/notifications/delete/{{ member.member_id }}/"><button class="btn btn-danger">Delete</button>
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
        <div class="row text-center">
            <div class="alert alert-warning col"> <strong>No Notifications</strong> </div>
        </div>
        {% endif %}

        <hr>

        <h3>Past Dues</h3>
        {% if evening_members_before %}
        <table class="table table-bordered">
            <thead class="thead-dark text-center">
                <tr>
			    <th>Profile Photo</th>
                    <th>Name</th>
                    <th>DOB</th>
                    <th>Registration Date</th>
                    <th>Registration End</th>
                    <th>Subscription Type</th>
                    <th>Pending Month</th>
                    <th>Edit</th>
                    <th>Delete Notification</th>
                </tr>
            </thead>
            <tbody class="text-center">
                {% for member in evening_members_before %}
                    <tr>	
				  <td><img src="{% if member.photo %}{{ member.photo.url }}{% else %}/media/default.jpg{% endif %}" class="img-fluid" width="100" height="100"></td>
                        <td>{{ member.first_name }} {{ member.last_name }}</td>
                        <td>{{ member.dob }}</td>
                        <td>{{ member.registration_date }}</td>
                        <td>{{ member.registration_upto }}</td>
                        <td>{{ member.get_subscription_type_display }}</td>
                        <td>{{ member.registration_upto|get_remaining_months}}</td>
                        <td>
                            <a href="/members/update/{{ member.member_id }}/"><button class="btn btn-success">Edit</button>
                            </a>
                        </td>
                        <td class="text-center">
                            <a href="/notifications/delete/{{ member.member_id }}/"><button class="btn btn-danger">Delete</button>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>

        {% else %}
        <div class="row text-center">
            <div class="alert alert-warning col"> <strong>No Notifications</strong> </div>
        </div>
        {% endif %}
      </div>
    </div>
{% endblock %}

{% block javascript %}
<script type="text/javascript">
  $(document).ready(function(){
      $('a[data-toggle="tab"]').on('show.bs.tab', function(e) {
          localStorage.setItem('activeTab', $(e.target).attr('href'));
      });
      var activeTab = localStorage.getItem('activeTab');
      if(activeTab){
          $('#myTab a[href="' + activeTab + '"]').tab('show');
      }
  });
  </script>
{% endblock %}